export const FOOD_ICONS = {
  apple: "🍎",
  banana: "🍌",
  orange: "🍊",
  carrot: "🥕",
  broccoli: "🥦",
  potato: "🥔",
  bottle: "🍼",
  cup: "☕",
  sandwich: "🥪",
  pizza: "🍕",
  cake: "🍰",
  donut: "🍩",
  bowl: "🍜",
  wine_glass: "🍷",
  hot_dog: "🌭",
  spoon: "🥄",
  knife: "🔪",
  fork: "🍴",
  default: "🥘",
};
